# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

# Llama-Swap config and run
# C:\Users\Ismael\apps\llama-swap\llama-swap.exe -watch-config -config c:\Users\Ismael\code\docs-llama-swap\config.yaml

metricsMaxInMemory: 10 # maximum records for metrics
sendLoadingState: true
logToStdout: "none"
includeAliasesInList: true

macros:
  "llamacpp-vulkan": C:\Users\Ismael\apps\llamacpp-vulkan\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1
  "llamacpp-vulkan-60k": C:\Users\Ismael\apps\llamacpp-vulkan\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 60000
  "llamacpp-vulkan-30k": C:\Users\Ismael\apps\llamacpp-vulkan\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 30000
  "llamacpp-vulkan-8k": C:\Users\Ismael\apps\llamacpp-vulkan\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 8000
  "llamacpp-vulkan-embed": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT}

  "llamacpp-rocm": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1
  "llamacpp-rocm-60k": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 60000
  "llamacpp-rocm-30k": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 30000
  "llamacpp-rocm-8k": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT} --no-mmap --jinja --parallel 1 --fit-ctx 8000
  "llamacpp-rocm-embed": C:\Users\Ismael\apps\llamacpp-rocm\llama-server.exe --port ${PORT}
  "sd-server": C:\Users\Ismael\apps\stablediffusioncpp-rocm\sd-server.exe --listen-port ${PORT} --diffusion-fa --verbose

models:

# text generation
  Qwen3-Coder-30B-A3B-Instruct:Q3_K_S:
    ttl: 1800 # seconds to unload the model after use
    cmd: | # support for multi-line
      ${llamacpp-vulkan-60k}
      -m F:/ai/lmstudio-models/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/Qwen3-Coder-30B-A3B-Instruct-Q3_K_S.gguf
      --batch-size 2048
      --temp 0.7
      --min-p 0.0
      --top-p 0.8
      --top-k 20
      --repeat-penalty 1.05
  GPT-OSS:20b:
    ttl: 1800 # seconds to unload the model after use
    cmd: | # support for multi-line
      ${llamacpp-vulkan-60k}
      --grammar-file F:\ai\lmstudio-models\lmstudio-community\gpt-oss-20b-GGUF\gpt-oss.gbnf
      -m F:\ai\lmstudio-models\lmstudio-community\gpt-oss-20b-GGUF\gpt-oss-20b-MXFP4.gguf
      --temp 1.0
      --top-p 1.0
      -b 2056 -ub 256
      --repeat-penalty 1.0 --repeat-last-n 200
      --cache-type-k q8_0 --cache-type-v q8_0
      --ctx-size 60000
  nomic-embed-text-v2-moe:q8_0:
    aliases:
      - embedding
    ttl: 1800 # seconds to unload the model after use
    cmd: |
      ${llamacpp-vulkan-embed}
      -m F:\ai\lmstudio-models\ggml-org\Nomic-Embed-Text-V2-GGUF\nomic-embed-text-v2-moe-q8_0.gguf
      --batch-size 8192
      --rope-scaling yarn
      --rope-freq-scale 0.75
      -ngl 99
      --embeddings
      --no-mmap
  Qwen3-Embedding-0.6B:Q8_0:
    ttl: 1800 # seconds to unload the model after use
    cmd: |
      ${llamacpp-vulkan-embed}
      -m F:\ai\lmstudio-models\Qwen\Qwen3-Embedding-0.6B-GGUF\Qwen3-Embedding-0.6B-Q8_0.gguf
      --batch-size 8192
      --rope-scaling yarn
      --rope-freq-scale 0.75
      -ngl 99
      --embeddings
      --no-mmap
  Qwen3.5-35B-A3B:Q4_K_M:
    ttl: 1800 # seconds to unload the model after use
    filters:
      stripParams: "temperature, top_k, top_p, repeat_penalty, min_p, presence_penalty"
      setParamsByID:
        "${MODEL_ID}-r.c":
          temperature: 0.6
          presence_penalty: 0.0
        "${MODEL_ID}-i":
          chat_template_kwargs:
            enable_thinking: false
          temperature: 0.7
          top_p: 0.8
    cmd: |
      ${llamacpp-vulkan-60k}
      --model F:/ai/lmstudio-models/lmstudio-community/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-Q4_K_M.gguf
      --temp 1.0 --min-p 0.0 --top-k 20 --top-p 0.95 --repeat_penalty 1.0 --presence_penalty 1.5

  Qwen3.5-35B-A3B:Q4_K_M-v:
    ttl: 1800 # seconds to unload the model after use
    filters:
      stripParams: "temperature, top_k, top_p, repeat_penalty, min_p, presence_penalty"
    cmd: |
      ${llamacpp-vulkan-60k}
      --model F:/ai/lmstudio-models/lmstudio-community/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-Q4_K_M.gguf
      --mmproj F:\ai\lmstudio-models\lmstudio-community\Qwen3.5-35B-A3B-GGUF\mmproj-Qwen3.5-35B-A3B-BF16.gguf
      --chat-template-kwargs "{\"enable_thinking\": false}"
      --temp 0.6 --top-p 0.95 --top-k 20 --min-p 0.0 --presence_penalty 0.0 --repeat_penalty 1.0

# audio transcription
  whisper-small:
    ttl: 1800 # seconds to unload the model after use
    cmd: | 
      C:\Users\Ismael\apps\whispercpp\whisper-server.exe
      --host 127.0.0.1
      --port ${PORT}
      -m F:\ai\audio-models\ggml-small.bin
      --request-path /v1/audio/transcriptions
      --inference-path ""
      --convert
      -l auto
      -pp
      -pr
    checkEndpoint: /v1/audio/transcriptions/
    env:
      - "RESPONSE_FORMAT=TXT"
  whisper-large-v3-turbo:
    ttl: 1800 # seconds to unload the model after use
    cmd: | 
      C:\Users\Ismael\apps\whispercpp\whisper-server.exe
      --host 127.0.0.1
      --port ${PORT}
      -m F:\ai\audio-models\ggml-large-v3-turbo.bin
      --request-path /v1/audio/transcriptions
      --inference-path ""
      --convert
      -l auto
      -pp
      -pr
    checkEndpoint: /v1/audio/transcriptions/
    env:
      - "RESPONSE_FORMAT=TXT"
  whisper-large-v3-turbo:Q5_0:
    ttl: 1800 # seconds to unload the model after use
    cmd: | 
      C:\Users\Ismael\apps\whispercpp\whisper-server.exe
      --host 127.0.0.1
      --port ${PORT}
      -m "F:\ai\audio-models\ggml-large-v3-turbo-q5_0.bin"
      --request-path /v1/audio/transcriptions
      --inference-path ""
      --convert
      -l auto
      -pp
      -pr
    checkEndpoint: /v1/audio/transcriptions/
    env:
      - "RESPONSE_FORMAT=TXT"
      

# image generation
  Z-Image-Turbo:Q4_K_M:
    checkEndpoint: "/"
    cmd: |
      ${sd-server}
      --diffusion-model F:\ai\lmstudio-models\unsloth\Z-Image-Turbo-GGUF\z-image-turbo-Q4_K_M.gguf
      --llm F:\ai\lmstudio-models\unsloth\Qwen3-4B-Instruct-2507\Qwen3-4B-Instruct-2507-UD-Q4_K_XL.gguf
      --vae F:\ai\stability-matrix\Data\Models\VAE\ae.safetensors
      --lora-model-dir F:\ai\stability-matrix\Data\Models\Lora
      --cfg-scale 1.0
      --steps 8

groups:
  group1:
    swap: false
    members:
      - "gpt-oss-20b-mxfp4"
      - "nomic-embed-text-v2-moe-q8_0"
      - "qwen3-embedding-0.6b-q8_0"
